import Sidebar from "./components/Sidebar";
import "../globals.css"

export const metadata = {
  title: "UniSecureShare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Sidebar />
      <main className="w-full overflow-y-scroll min-h-screen">{children}</main>
    </>
  );
}
