export const announcements = [
  {
    id: 1,
    title: "BTech CSE - Sem 1 Timetable",
    date: "15/11/2024",
    url: "",
    downloadable: true,
    isPrivateFile: false,
    isAnnouncement: true,
    tag: "time-table",
  },
  {
    id: 2,
    title: "BTech CSE - Sem 3 Timetable",
    date: "15/11/2024",
    url: "",
    downloadable: true,
    isPrivateFile: false,
    isAnnouncement: true,
    tag: "time-table",
  },
  {
    id: 3,
    title: "Exam Schedule 2024-25",
    date: "10/11/2024",
    url: "",
    downloadable: true,
    isPrivateFile: false,
    isAnnouncement: true,
    tag: "datesheet",
  },
  {
    id: 4,
    title: "Microprocessor 8085 Datasheet",
    date: "20/10/2024",
    url: "",
    downloadable: true,
    isPrivateFile: false,
    isAnnouncement: true,
    tag: "resource",
  },
  {
    id: 5,
    title: "Arduino UNO Datasheet",
    date: "18/10/2024",
    url: "",
    downloadable: true,
    isPrivateFile: false,
    isAnnouncement: true,
    tag: "resource",
  },
  {
    id: 6,
    title: "FPGA Development Guide",
    date: "12/10/2024",
    url: "",
    downloadable: true,
    isPrivateFile: false,
    isAnnouncement: true,
    tag: "time-table",
  },
  {
    id: 7,
    title: "Web Development Workshop 2024",
    date: "25/11/2024",
    url: "",
    downloadable: true,
    isPrivateFile: false,
    isAnnouncement: true,
    tag: "workshop",
  },
  {
    id: 8,
    title: "AI & ML Workshop Materials",
    date: "22/11/2024",
    url: "",
    downloadable: true,
    isPrivateFile: false,
    isAnnouncement: true,
    tag: "workshop",
  },
  {
    id: 9,
    title: "Cloud Computing Workshop",
    date: "20/11/2024",
    url: "",
    downloadable: true,
    isPrivateFile: false,
    isAnnouncement: true,
    tag: "workshop",
  },
  {
    id: 10,
    title: "Hackathon Rules & Guidelines",
    date: "01/12/2024",
    url: "",
    downloadable: true,
    isPrivateFile: false,
    isAnnouncement: true,
    tag: "hackathon",
  },
  {
    id: 11,
    title: "Hackathon Problem Statements",
    date: "01/12/2024",
    url: "",
    downloadable: true,
    isPrivateFile: false,
    isAnnouncement: true,
    tag: "hackathon",
  },
  {
    id: 12,
    title: "Hackathon Judging Criteria",
    date: "01/12/2024",
    url: "",
    downloadable: true,
    isPrivateFile: false,
    isAnnouncement: true,
    tag: "hackathon",
  },
  {
    id: 13,
    title: "Industry Expert Talk - Cloud & DevOps",
    date: "28/11/2024",
    url: "",
    downloadable: true,
    isPrivateFile: false,
    isAnnouncement: true,
    tag: "time-table",
  },
  {
    id: 14,
    title: "Cybersecurity Seminar Slides",
    date: "25/11/2024",
    url: "",
    downloadable: true,
    isPrivateFile: false,
    isAnnouncement: true,
    tag: "time-table",
  },
  {
    id: 15,
    title: "Data Science in 2024 - Seminar Notes",
    date: "20/11/2024",
    url: "",
    downloadable: true,
    isPrivateFile: false,
    isAnnouncement: true,
    tag: "time-table",
  },
];

export const classes = [
  {
    course: "BTech",
    branch: "CSE",
    section: "A",
    semester: 1,
    classId: "BTECH-CSE-A-SEM1",
    text: "BTech CSE - Section A - Sem 1",
  },
  {
    course: "BTech",
    branch: "CSE",
    section: "B",
    semester: 1,
    classId: "BTECH-CSE-B-SEM1",
    text: "BTech CSE - Section B - Sem 1",
  },
  {
    course: "BTech",
    branch: "CSE",
    section: "C",
    semester: 1,
    classId: "BTECH-CSE-C-SEM1",
    text: "BTech CSE - Section C - Sem 1",
  },
  {
    course: "BTech",
    branch: "CSE",
    section: "A",
    semester: 3,
    classId: "BTECH-CSE-A-SEM3",
    text: "BTech CSE - Section A - Sem 3",
  },
  {
    course: "BTech",
    branch: "CSE",
    section: "A",
    semester: 5,
    classId: "BTECH-CSE-A-SEM5",
    text: "BTech CSE - Section A - Sem 5",
  },
];

export const filesData = [
  {
    classId: "BTECH-CSE-A-SEM1",
    files: [
      {
        id: 1,
        title: "Linux File System Hierarchy",
        date: "19/11/2023",
        tag: "notes",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "public",
      },
      {
        id: 2,
        title: "User and Group Management",
        date: "19/11/2023",
        tag: "assignments",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "public",
      },
      {
        id: 3,
        title: "File Permissions and Ownership",
        date: "19/11/2023",
        tag: "notes",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "hidden",
      },
      {
        id: 4,
        title: "Shell Scripting Basics",
        date: "19/11/2023",
        tag: "assignments",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "public",
      },
      {
        id: 5,
        title: "Linux Installation and Setup",
        date: "19/11/2023",
        tag: "notes",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "hidden",
      },
    ],
  },
  {
    classId: "BTECH-CSE-B-SEM1",
    files: [
      {
        id: 6,
        title: "Command Line Interface Essentials",
        date: "15/11/2023",
        tag: "notes",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "public",
      },
      {
        id: 7,
        title: "Process Management in Linux",
        date: "15/11/2023",
        tag: "assignments",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "hidden",
      },
      {
        id: 8,
        title: "Directory Navigation",
        date: "15/11/2023",
        tag: "notes",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "public",
      },
      {
        id: 9,
        title: "Text Processing Tools",
        date: "15/11/2023",
        tag: "assignments",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "public",
      },
    ],
  },
  {
    classId: "BTECH-CSE-C-SEM1",
    files: [
      {
        id: 10,
        title: "System Administration Fundamentals",
        date: "10/11/2023",
        tag: "notes",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "public",
      },
      {
        id: 11,
        title: "Package Management Systems",
        date: "10/11/2023",
        tag: "assignments",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "hidden",
      },
      {
        id: 12,
        title: "Network Configuration Basics",
        date: "10/11/2023",
        tag: "notes",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "public",
      },
    ],
  },
  {
    classId: "BTECH-CSE-A-SEM3",
    files: [
      {
        id: 13,
        title: "Advanced Shell Scripting",
        date: "20/11/2023",
        tag: "notes",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "public",
      },
      {
        id: 14,
        title: "System Logging and Monitoring",
        date: "20/11/2023",
        tag: "assignments",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "public",
      },
      {
        id: 15,
        title: "Backup and Recovery Strategies",
        date: "20/11/2023",
        tag: "notes",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "public",
      },
      {
        id: 16,
        title: "Security Hardening",
        date: "20/11/2023",
        tag: "assignments",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "public",
      },
    ],
  },
  {
    classId: "BTECH-CSE-A-SEM5",
    files: [
      {
        id: 17,
        title: "Kernel Configuration and Compilation",
        date: "25/11/2023",
        tag: "notes",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "public",
      },
      {
        id: 18,
        title: "Advanced User Management",
        date: "25/11/2023",
        tag: "assignments",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "public",
      },
      {
        id: 19,
        title: "Storage Management",
        date: "25/11/2023",
        tag: "notes",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "public",
      },
      {
        id: 20,
        title: "Virtualization and Containers",
        date: "25/11/2023",
        tag: "assignments",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "hidden",
      },
      {
        id: 21,
        title: "Performance Tuning",
        date: "25/11/2023",
        tag: "notes",
        url: "",
        downloadable: false,
        isPrivateFile: false,
        isAnnouncement: false,
        access: "public",
      },
    ],
  },
];

export const logs = [
  {
    fileId: 1,
    logs: [
      "Rahul (2581101) viewed the file",
      "Ananya (2581123) viewed the file",
      "Soham (2581145) viewed the file",
      "Neha (2581189) viewed the file",
      "Rahul (2581101) viewed the file again",
    ],
  },
  {
    fileId: 2,
    logs: [
      "Soham (2581145) viewed the file",
      "Arjun (2581210) viewed the file",
      "Neha (2581189) viewed the file",
      "Ananya (2581123) viewed the file",
      "Soham (2581145) viewed the file again",
    ],
  },
  {
    fileId: 3,
    logs: [
      "Neha (2581189) viewed the file",
      "Rahul (2581101) viewed the file",
      "Priya (2581256) viewed the file",
      "Ananya (2581123) viewed the file",
      "Neha (2581189) viewed the file again",
      "Rahul (2581101) viewed the file again",
    ],
  },
  {
    fileId: 4,
    logs: [
      "Arjun (2581210) viewed the file",
      "Soham (2581145) viewed the file",
      "Rahul (2581101) viewed the file",
      "Ananya (2581123) viewed the file",
      "Arjun (2581210) viewed the file again",
    ],
  },
  {
    fileId: 5,
    logs: [
      "Priya (2581256) viewed the file",
      "Neha (2581189) viewed the file",
      "Rahul (2581101) viewed the file",
      "Ananya (2581123) viewed the file",
      "Priya (2581256) viewed the file again",
    ],
  },
];

export const privateFiles = [
  {
    fileId: 1,
    title: "Assignment 1",
    date: "20/11/2024",
    tag: "assignment",
    isPrivateFile: true,
    isAnnouncement: false,
    downloadable: true,
  },
  {
    fileId: 2,
    title: "Assignment 2",
    date: "18/11/2024",
    tag: "assignment",
    isPrivateFile: true,
    isAnnouncement: false,
    downloadable: true,
  },
  {
    fileId: 3,
    title: "Study Notes - Chapter 5",
    date: "15/11/2024",
    tag: "notes",
    isPrivateFile: true,
    isAnnouncement: false,
    downloadable: true,
  },
  {
    fileId: 4,
    title: "Project Report",
    date: "10/11/2024",
    tag: "project",
    isPrivateFile: true,
    isAnnouncement: false,
    downloadable: true,
  },
  {
    fileId: 5,
    title: "Exam Preparation",
    date: "08/11/2024",
    tag: "exam",
    isPrivateFile: true,
    isAnnouncement: false,
    downloadable: true,
  },
  {
    fileId: 6,
    title: "Lab Experiment Data",
    date: "05/11/2024",
    tag: "lab",
    isPrivateFile: true,
    isAnnouncement: false,
    downloadable: true,
  },
];

export const role = "student"; // student or faculty
