import { Averia_Serif_Libre, Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["serif"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const averiaSerif = Averia_Serif_Libre({
  variable: "--font-averia",
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap", 
});

export const metadata = {
  title: "UniSecureShare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${averiaSerif.variable} ${poppins.variable} antialiased h-fit lg:max-h-screen`}
      >
        <Sidebar />
        <main className="w-full overflow-y-scroll min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
